=== JonatanSwDev/2021-2023-DAM/2023 - 2 DAM/Lenguaje de Marcas/03_XML/DTD/Ejercicio30.dtd
<!ELEMENT urbanizacion (casa+)>
	<!ELEMENT casa (cocina, aseo1, aseo2?, salon, dormitorio1, dormitorio2?)>
  <!ATTLIST casa portal NMTOKEN #REQUIRED>
	<!ELEMENT cocina (#PCDATA)>
	<!ELEMENT aseo1 (#PCDATA)>
	<!ELEMENT aseo2 (#PCDATA)>
	<!ELEMENT salon (#PCDATA)>
	<!ELEMENT dormitorio1 (#PCDATA)>
	<!ELEMENT dormitorio2 (#PCDATA)>

=== JonatanSwDev/2021-2023-DAM/2023 - 2 DAM/Lenguaje de Marcas/03_XML/DTD/Ejercicio30.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE urbanizacion SYSTEM "Ejercicio30.dtd">
<urbanizacion>
 <casa portal="1-A">
   <cocina>25m.</cocina>
   <aseo1>10m</aseo1>
   <aseo2>15m</aseo2>
   <salon>35m</salon>
   <dormitorio1>18m</dormitorio1>
   <dormitorio2>24m</dormitorio2>
 </casa>
 <casa portal="1-B">
   <cocina>25m.</cocina>
   <aseo1>10m</aseo1>
   <aseo2>15m</aseo2>
   <salon>35m</salon>
   <dormitorio1>18m</dormitorio1>
 </casa>
</urbanizacion>
