=== JonatanSwDev/2021-2023-DAM/2023 - 2 DAM/Lenguaje de Marcas/03_XML/DTD/Ejercicio34.dtd
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (nombre, apellidos, domicilio, telefono, equipo_deportivo?, aficion*,(provincia|origen), comentario, notas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT equipo_deportivo (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT comentario ANY>
<!ELEMENT notas (evaluacion, calificacion)>
<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>
<!ATTLIST alumno num_alumno ID #REQUIRED >
<!ATTLIST alumno altura CDATA #IMPLIED >
<!ATTLIST alumno sexo (hombre | mujer) #IMPLIED >
<!ATTLIST telefono tipo (propio | padre | madre | tutor) #REQUIRED >
<!ATTLIST alumno ayudante IDREF #IMPLIED >

=== JonatanSwDev/2021-2023-DAM/2023 - 2 DAM/Lenguaje de Marcas/03_XML/DTD/Ejercicio34.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "Ejercicio34.dtd" >
<alumnos>
  <alumno num_alumno="A1" altura="180" sexo="hombre" ayudante="A2">
    <nombre>Juan</nombre>
    <apellidos>Pérez</apellidos>
    <domicilio>Calle Falsa 123</domicilio>
    <telefono tipo="propio">555-555-555</telefono>
    <equipo_deportivo>Equipo de Futbol</equipo_deportivo>
    <aficion>Leer</aficion>
    <aficion>Viajar</aficion>
    <provincia>Madrid</provincia>
    <comentario>Este alumno es muy responsable</comentario>
    <notas>
      <evaluacion>Examen de Matemáticas</evaluacion>
      <calificacion>8</calificacion>
    </notas>
  </alumno>
  <alumno num_alumno="A2">
    <nombre>Maria</nombre>
    <apellidos>Garcia</apellidos>
    <domicilio>Calle Falsa 124</domicilio>
    <telefono tipo="padre">555-555-556</telefono>
    <origen>Inglaterra</origen>
    <comentario>Esta alumna es muy tímida</comentario>
    <notas>
      <evaluacion>Examen de Literatura</evaluacion>
      <calificacion>10</calificacion>
    </notas>
  </alumno>
</alumnos>
