=== JonatanSwDev/2021-2023-DAM/2023 - 2 DAM/Lenguaje de Marcas/03_XML/DTD/Ejercicio31.dtd
<!ELEMENT peliculas (pelicula*)>
  <!ELEMENT pelicula (((titulo, director) | (director, titulo)), autor)>
  <!ELEMENT autor (#PCDATA)>  
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT director (#PCDATA)>

=== JonatanSwDev/2021-2023-DAM/2023 - 2 DAM/Lenguaje de Marcas/03_XML/DTD/Ejercicio31.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peliculas SYSTEM "Ejercicio31.dtd">
<peliculas>
  <pelicula>
    <titulo>Con faldas y a lo loco</titulo>
    <director>Billy Wilder</director>
    <autor>paco</autor>
  </pelicula>
  <pelicula>
    <director>Leo McCarey</director>
    <titulo>Sopa de ganso</titulo>
    <autor>barto</autor>
  </pelicula>
</peliculas>
